<a href="https://colab.research.google.com/github/abdullateefogundipe/abdullateefogundipe/blob/main/Predicting%20region%20of%20a%20terrorist%20attack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("/content/drive/MyDrive/Hamoye/clean_df.csv", index_col=[0])

In [7]:
!pip install colorama

In [8]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as plb
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer
plt.style.use('seaborn')
from colorama import Style, Fore, Back
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from imblearn.over_sampling import RandomOverSampler
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [9]:

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report, confusion_matrix

### **PREDICTING REGION OF A TERRORIST ATTACK**

In [10]:
# function to display UNIQUE examples of data in each field

def getDesc(data, Column, numExamples=5):
    x = list(set([i for i in data[Column] if i==i]))
    if len(x)<numExamples:
        numExamples = len(x)
    x = list(np.random.choice(x, size=numExamples, replace=False))
    print('Examples in '+Style.BRIGHT+Back.CYAN+Column+Back.RESET+':'+Style.RESET_ALL, x, '\n')
    return None

# ======================================================================================

# function to display the number of missing values in each field

def getNumNan(data, thisFeature):
    ms = data[data[thisFeature] != data[thisFeature]].shape[0]
    print('Missing values in '+Style.BRIGHT+Back.CYAN+thisFeature+Back.RESET+Style.RESET_ALL+': {}'.format(ms))
    return None

In [11]:
for i in df.columns:
    getNumNan(df, i)
    getDesc(df, i, 7)

Missing values in Year: 0
Examples in Year: [1989, 1990, 2005, 1971, 1996, 2007, 2004] 

Missing values in Month: 0
Examples in Month: [12, 2, 3, 9, 5, 10, 0] 

Missing values in Day: 0
Examples in Day: [25, 19, 14, 23, 8, 21, 26] 

Missing values in Extended: 0
Examples in Extended: [0, 1] 

Missing values in Country: 0
Examples in Country: ['Grenada', 'Vietnam', 'Wallis and Futuna', 'Mexico', 'Jamaica', 'Kosovo', 'International'] 

Missing values in Region: 0
Examples in Region: ['East Asia', 'Sub-Saharan Africa', 'Western Europe', 'South America', 'North America', 'Southeast Asia', 'Middle East & North Africa'] 

Missing values in City: 0
Examples in City: ['Nueva Espana', 'Abu Mohammed', 'Barha', 'Bairam-Aul', 'Rechelim', 'Polampalli', 'Rio Hondo'] 

Missing values in Success: 0
Examples in Success: [1, 0] 

Missing values in Suicide: 0
Examples in Suicide: [1, 0] 

Missing values in Attack_Type: 0
Examples in Attack_Type: ['Facility/Infrastructure Attack', 'Assassination', 'Bombin

In [12]:
cat_col = ['Success','Suicide', 'natlty1', 'weaptype1', 'attacktype1', 'targtype1', 'Year', 'Month', 'Day', 'Extended','Property','country', 'region']
for col in cat_col:
  df[col] = df[col].astype("category")

In [14]:
df = df.drop(columns = ['Month','Day','City','target1', 'gname', 'Country', 'Region','Target', 'Attack_Type','Target_Type', 'Target_Subtype', 'Target','Target_Nationality','Attack_Group', 'Weapon'])


In [15]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
X = df.loc[:, df.columns != 'region']
X.head()

Year Extended Success Suicide  No_Of_Killed  No_Of_Wounded Property  \
0  1970        0       1       0           1.0            0.0        0   
1  1970        0       1       0           0.0            0.0        0   
2  1970        0       1       0           1.0            0.0        0   
3  1970        0       1       0           0.0            0.0        1   
4  1970        0       1       0           0.0            0.0        1   

  country attacktype1 targtype1 natlty1 weaptype1  
0      58           1        14    58.0        13  
1     130           6         7    21.0        13  
2     160           1        10   217.0        13  
3      78           3         7   217.0         6  
4     101           7         7   217.0         8

In [20]:
y = df["region"]
y.value_counts()

10    50474
6     44974
3     18978
11    17550
8     16639
5     12485
2     10344
9      5144
1      3456
4       802
7       563
12      282
Name: region, dtype: int64

In [22]:
# Split dataset into a training and testing set.
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [33]:
print ('Number of observations in the target variable before oversampling of the minority class:', np.bincount (y_train) )

ros = RandomOverSampler (random_state=2)
X_train, y_train = ros.fit_resample (X_train, y_train)

print ('\nNumber of observations in the target variable after oversampling of the minority class:', np.bincount (y_train) )

Number of observations in the target variable before oversampling of the minority class: [    0 35252 35252 35252 35252 35252 35252 35252 35252 35252 35252 35252
 35252]

Number of observations in the target variable after oversampling of the minority class: [    0 35252 35252 35252 35252 35252 35252 35252 35252 35252 35252 35252
 35252]


In [34]:
data_dict = {"X_train":X_train, "X_test":X_test, "y_train":y_train, "y_test":y_test}
for i in data_dict:
    print("The shape of {} is {}".format(i,data_dict[i].shape))

The shape of X_train is (423024, 12)
The shape of X_test is (54508, 12)
The shape of y_train is (423024,)
The shape of y_test is (54508,)


In [25]:
sc =StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [44]:
clf = [ LogisticRegression(random_state=2), DecisionTreeClassifier(random_state=2), SVC (random_state=2),
       RandomForestClassifier(random_state=2), GradientBoostingClassifier(random_state=2) ]
models = [ 'Logistic Regression', 'Tree', 'Support vector machine', 'RFC', 'Gradient boost' ]



In [ ]:
for i in range(0, len(clf)):
        text_clf = Pipeline([('clf', clf[i])])
        print(text_clf)
        text_clf.fit(X_train, y_train)  
        predictions = text_clf.predict(X_test)
        
        print(metrics.confusion_matrix(y_test,predictions))
        print(metrics.classification_report(y_test,predictions))
        print('F1_score: ',round(metrics.f1_score(y_test,predictions, average = 'weighted'),3))
        print('-------------------------------------------------------')

Pipeline(steps=[('clf', LogisticRegression(random_state=2))])
[[ 683   30    7   20   46   14   56   56   30   23   76   18]
 [  81 2057  323  150    1    7  101  142    1    6   10  137]
 [ 556 2000  719  230   31  404  386  760   15   79   55  425]
 [  28   22   48   29    1   34   11    2    2    8    3   66]
 [ 260   59   72   95 1303   82  257  165  562  143  701   84]
 [ 459  305  441  484 1608 5228  538  209  571 1228 1678  687]
 [  10    6   24    7   21   23   13   10    5   11   18   17]
 [ 777  798  274  147   86  281  111 1696  273   26   50  514]
 [  48    7   49   11  363   20   81  119  482   27  250   40]
 [ 663  574  644  426  593 5810  470  252  919 3172 1306  393]
 [ 493  163  105  122  791  448  165  160  533  425 1806   79]
 [   8   13    4    3    3    7   14   22    2    0    1   16]]
              precision    recall  f1-score   support

           1       0.17      0.64      0.27      1059
           2       0.34      0.68      0.45      3016
           3      